Repository AY2425S1-CS2113-T10-3/tp, pull requests merged in 2024-11, with the labels that each got.

#98 Branch sales parser fix
  docs/UserGuide.md
  src/main/java/commands/AddSalesCommand.java
  src/main/java/constants/Regex.java
  src/main/java/exceptions/AuthorDoesNotExistException.java
  src/main/java/exceptions/InvalidSalesCommandException.java
  src/main/java/exceptions/MangaDoesNotExistException.java
  src/main/java/exceptions/NoPriceProvidedException.java
  src/main/java/exceptions/NoQuantityProvidedException.java
  src/main/java/exceptions/NumberLessThanZeroException.java
  src/main/java/exceptions/SalesArgsWrongOrderException.java
  src/main/java/manga/Manga.java
  src/main/java/parser/Parser.java
  src/main/java/parser/PriceArgumentFinder.java
  src/main/java/parser/QuantityArgumentFinder.java
  src/main/java/sales/Sale.java
  src/test/java/commands/AddSalesCommandTest.java
  src/test/java/parser/ParserTest.java
Labels: type.Task, type.Bug, priority.High

#106 Add JUnit tests for view commands
  src/main/java/commands/ViewAuthorsCommand.java
  src/main/java/commands/ViewMangasCommand.java
  src/main/java/exceptions/AuthorDoesNotExistException.java
  src/main/java/exceptions/AuthorListEmptyException.java
  src/main/java/exceptions/MangaListEmptyException.java
  src/test/java/commands/ViewAuthorsCommandTest.java
  src/test/java/commands/ViewMangasCommandTest.java
  src/test/resources/testCatalog.json
Labels: type.Task, priority.High

#103 Branch UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#100 Serialize sales data
  docs/DeveloperGuide.md
  src/main/java/manga/Manga.java
  src/main/java/manga/MangaList.java
  src/main/java/sales/Sale.java
  src/main/java/storage/AuthorListDeserializer.java
  src/main/java/storage/MangaDeserializer.java
  src/main/java/storage/MangaListDeserializer.java
  src/main/java/storage/SaleDeserializer.java
  src/test/java/storage/AuthorListDeserializerTest.java
  src/test/java/storage/MangaListDeserializerTest.java
  src/test/java/storage/SaleDeserializerTest.java
  src/test/java/storage/StorageTest.java
  src/test/resources/testCatalog.json
Labels: type.Task, priority.High

#109 Update DG with content regarding Parsing Architecture
  docs/DeveloperGuide.md
  docs/uml/puml/Parser/Parser.png
  docs/uml/puml/Parser/Parser.puml
Labels: type.Task, priority.Medium

#104 Configure global setup and teardown for JUnit tests
  build.gradle
  src/test/java/session/GlobalSetupTearDownListener.java
  src/test/java/storage/StorageTest.java
  src/test/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener
  src/test/resources/storageTestCatalog.json
Labels: type.Bug, priority.Low, severity.Low

#99 Updated schedule to work with the new parser
  src/main/java/commands/AddDeadlineCommand.java
  src/main/java/constants/Command.java
  src/main/java/constants/Regex.java
  src/main/java/exceptions/InvalidScheduleCommandException.java
  src/main/java/exceptions/NoDeadlineProvidedException.java
  src/main/java/manga/Manga.java
  src/main/java/parser/DeadlineArgumentFinder.java
  src/main/java/parser/Parser.java
  src/test/java/commands/AddDeadlineCommandTest.java
Labels: type.Task, priority.High

#101 DG - Schedule
  docs/DeveloperGuide.md
  docs/uml/images/schedule.png
  docs/uml/puml/schedule.puml
  src/main/java/commands/AddDeadlineCommand.java
Labels: priority.Medium, type.Information

#114 Branch stress test
  docs/DeveloperGuide.md
  src/main/java/commands/AddDeadlineCommand.java
  src/main/java/constants/Regex.java
  src/main/java/parser/DeadlineArgumentFinder.java
  src/main/java/parser/Parser.java
  src/test/java/commands/AddDeadlineCommandTest.java
Labels: type.Task, priority.High

#115 DG updates
  docs/DeveloperGuide.md
  docs/regexDiagram.png
  docs/uml/puml/AuthorListClass/AuthorListClass.png
  docs/uml/puml/AuthorListClass/AuthorListClass.puml
  docs/uml/puml/UiClass/UiClass.png
  docs/uml/puml/UiClass/UiClass.puml
Labels: type.Task, priority.High

#121 Change log message output to a file
  .gitignore
  src/main/java/Main.java
  src/main/java/commands/AddAuthorCommand.java
  src/main/java/commands/AddDeadlineCommand.java
  src/main/java/commands/AddMangaCommand.java
  src/main/java/commands/AddSalesCommand.java
  src/main/java/commands/Command.java
  src/main/java/commands/DeleteAuthorCommand.java
  src/main/java/commands/DeleteMangaCommand.java
  src/main/java/commands/ViewAuthorsCommand.java
  src/main/java/commands/ViewMangasCommand.java
  src/main/java/storage/Storage.java
  src/main/java/tantou/Tantou.java
Labels: type.Task, priority.High

#123 Branch update ppp and dg
  docs/DeveloperGuide.md
  docs/team/chengjiaweiandy.md
  docs/uml/images/AddAuthorSequence.png
  docs/uml/images/AddMangaSequence.png
  docs/uml/images/DeleteAuthorSequence.png
  docs/uml/images/DeleteMangaSequence.png
  docs/uml/puml/AddAuthorSequence.puml
  docs/uml/puml/AddMangaSequence.puml
  docs/uml/puml/DeleteAuthorSequence.puml
  docs/uml/puml/DeleteMangaSequence.puml
  src/main/java/commands/AddAuthorCommand.java
  src/main/java/commands/AddMangaCommand.java
  src/main/java/commands/DeleteAuthorCommand.java
  src/main/java/commands/DeleteMangaCommand.java
  src/main/java/exceptions/AuthorExistsException.java
  src/main/java/exceptions/MangaExistsException.java
  src/main/java/ui/Ui.java
  src/test/java/commands/AddMangaCommandTest.java
  src/test/java/commands/DeleteAuthorCommandTest.java
  src/test/java/commands/DeleteMangaCommandTest.java
Labels: type.Task, priority.High

#117 Branch developer guide fix
  docs/DeveloperGuide.md
  docs/uml/images/AddSalesSequence.png
  docs/uml/images/CommandSequence.png
  docs/uml/images/MangaSalesClass.png
  docs/uml/images/addsalesdata.png
  docs/uml/images/mangasales_class.png
  docs/uml/images/mangasales_object.png
  docs/uml/puml/AddSalesSequence.puml
  docs/uml/puml/CommandSequence.puml
  docs/uml/puml/MangaSalesClass.puml
  docs/uml/puml/addsalesdata.puml
  docs/uml/puml/mangasales_object.puml
Labels: type.Bug, priority.Medium

#126 Schedule SD update
  docs/uml/images/schedule.png
  docs/uml/puml/schedule.puml
Labels: type.Task, priority.High

#129 Branch fix docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#130 Update link to Command Inheritance file
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#174 Remove redundant sout message in ViewMangasCommand
  src/main/java/commands/ViewMangasCommand.java
Labels: type.Bug, severity.VeryLow

#173 Make data and log files save to path relative to jar file
  .gitignore
  docs/UserGuide.md
  src/main/java/storage/Storage.java
  src/main/java/tantou/Tantou.java
Labels: type.Bug, severity.Low

#172 Ian's PPP
  docs/team/iaso1774.md
Labels: type.Task, priority.High

#175 Fix CommandSequence diagram
  docs/DeveloperGuide.md
  docs/uml/images/CommandSequence.png
  docs/uml/puml/CommandSequence.puml
Labels: type.Bug, priority.High

#176 Fix command exception messages
  src/main/java/commands/AddSalesCommand.java
  src/main/java/exceptions/NumberLessThanZeroException.java
  src/main/java/exceptions/PriceWrongFormatException.java
  src/main/java/exceptions/QuantityWrongFormatException.java
  src/test/java/commands/AddSalesCommandTest.java
Labels: type.Task, priority.Medium

#181 Fix manual data
  src/main/java/commands/AddSalesCommand.java
  src/main/java/constants/Options.java
  src/main/java/exceptions/PriceTooLargeException.java
  src/main/java/exceptions/QuantityTooLargeException.java
  src/main/java/storage/AuthorDeserializer.java
  src/main/java/storage/AuthorListDeserializer.java
  src/main/java/storage/MangaDeserializer.java
  src/main/java/storage/MangaListDeserializer.java
  src/main/java/storage/Storage.java
  src/test/java/storage/AuthorDeserializerTest.java
  src/test/java/storage/MangaDeserializerTest.java
Labels: type.Bug, severity.Medium

#177 Branch refactor UI
  docs/AboutUs.md
  docs/team/averageandyyy.md
  src/main/java/commands/AddDeadlineCommand.java
  src/main/java/commands/AddSalesCommand.java
  src/main/java/commands/ViewAuthorsCommand.java
  src/main/java/commands/ViewMangasCommand.java
  src/main/java/storage/AuthorListDeserializer.java
  src/main/java/storage/MangaListDeserializer.java
  src/main/java/storage/SaleDeserializer.java
  src/main/java/storage/Storage.java
  src/main/java/tantou/Tantou.java
  src/main/java/ui/Ui.java
Labels: type.Task, priority.High

#170 Fix issues brought up with Schedule in the PED
  docs/UserGuide.md
Labels: type.Task, priority.High

#182 Branch validity checks
  src/main/java/author/Author.java
  src/main/java/commands/AddAuthorCommand.java
  src/main/java/commands/AddDeadlineCommand.java
  src/main/java/commands/AddMangaCommand.java
  src/main/java/commands/AddSalesCommand.java
  src/main/java/commands/Command.java
  src/main/java/commands/CommandValidator.java
  src/main/java/commands/DeleteAuthorCommand.java
  src/main/java/commands/DeleteMangaCommand.java
  src/main/java/commands/ViewAuthorsCommand.java
  src/main/java/commands/ViewMangasCommand.java
  src/main/java/constants/Options.java
  src/main/java/constants/PrintFormat.java
  src/main/java/exceptions/AuthorDoesNotExistException.java
  src/main/java/exceptions/DeadlineTooLongException.java
  src/main/java/exceptions/MangaDoesNotExistException.java
  src/main/java/exceptions/PriceTooLargeException.java
  src/main/java/exceptions/QuantityTooLargeException.java
  src/main/java/exceptions/QuantityWrongFormatException.java
  src/main/java/storage/AuthorDeserializer.java
  src/main/java/storage/AuthorListDeserializer.java
  src/main/java/storage/MangaDeserializer.java
  src/main/java/storage/MangaListDeserializer.java
  src/main/java/storage/SaleDeserializer.java
  src/main/java/tantou/Tantou.java
  src/main/java/ui/Ui.java
  src/test/java/storage/AuthorDeserializerTest.java
  src/test/java/storage/AuthorListDeserializerTest.java
  src/test/java/storage/MangaDeserializerTest.java
  src/test/java/storage/MangaListDeserializerTest.java
  src/test/java/storage/SaleDeserializerTest.java
Labels: type.Bug, severity.Medium

#184 Branch finalise dg
  docs/DeveloperGuide.md
  docs/team/averageandyyy.md
  docs/uml/puml/Command/Command_One.png
  docs/uml/puml/Command/Command_One.puml
  docs/uml/puml/Command/Command_Three.png
  docs/uml/puml/Command/Command_Three.puml
  docs/uml/puml/Command/Command_Two.png
  docs/uml/puml/Command/Command_Two.puml
  docs/uml/puml/Parser/Parser_One.puml
Labels: type.Task, priority.High

#119 Donovan's PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/johndoe.md
  docs/team/xenthm.md
Labels: type.Task, priority.High

#187 Fix Sarah's PPP
  docs/team/sarahchow03.md
Labels: type.Bug, priority.Medium

#185 Final fixes
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/commands/AddSalesCommand.java
  src/main/java/storage/SaleDeserializer.java
Labels: type.Task, priority.High

#189 Try another horizontal line in DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#190 Fixes to images in DG
  docs/uml/puml/SavingDataSequence/SavingDataSequence.png
  docs/uml/puml/ViewMangaSequence/refGetColumnsToPrintSequence.png
Labels: type.Bug, priority.High
