Repository AY2425S1-CS2113-T10-3/tp, pull requests merged in 2024-10, with the labels that each got.

#17 Branch fix input command format
  src/main/java/constants/Options.java
  src/main/java/constants/Regex.java
  src/main/java/parser/Parser.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Bug

#21 JUnit Tests for delete functionality
  src/test/java/commands/DeleteAuthorCommandTest.java
  src/test/java/commands/DeleteMangaCommandTest.java
  src/test/java/parser/ParserTest.java
Labels: priority.High

#29 Added functionality to add, view, and delete deadlines
  src/main/java/author/Author.java
  src/main/java/commands/AddDeadlineCommand.java
  src/main/java/commands/DeleteDeadlineCommand.java
  src/main/java/constants/Options.java
  src/main/java/manga/Manga.java
  src/main/java/manga/MangaList.java
  src/main/java/parser/Parser.java
  src/test/java/author/AuthorTest.java
  src/test/java/commands/AddDeadlineCommandTest.java
  src/test/java/commands/DeleteDeadlineCommandTest.java
  src/test/java/manga/MangaListTest.java
Labels: priority.High

#31 Amendments to JUnit Tests for deleteManga and deleteAuthor
  src/main/java/commands/DeleteAuthorCommand.java
  src/test/java/commands/DeleteAuthorCommandTest.java
  src/test/java/commands/DeleteMangaCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#32 Add assertions and logs for deleteManga and deleteAuthor
  src/main/java/commands/DeleteAuthorCommand.java
  src/main/java/commands/DeleteMangaCommand.java
Labels: type.Task, priority.High

#38 Branch assertion and logging add manga command
  build.gradle
  src/main/java/commands/AddAuthorCommand.java
  src/main/java/commands/AddMangaCommand.java
  src/main/java/commands/Command.java
  src/main/java/commands/DeleteAuthorCommand.java
  src/main/java/commands/DeleteMangaCommand.java
  src/main/java/parser/Parser.java
Labels: type.Task, priority.High

#37 Add Assertions and Logging for View commands
  src/main/java/author/AuthorList.java
  src/main/java/commands/ViewAuthorsCommand.java
  src/main/java/commands/ViewMangasCommand.java
Labels: type.Task, priority.High

#40 Added assertions and logging for deadline commands
  src/main/java/commands/AddDeadlineCommand.java
  src/main/java/commands/DeleteDeadlineCommand.java
  src/main/java/manga/Manga.java
Labels: type.Task, priority.High

#44 Implement Storage for data saving
  .gitignore
  build.gradle
  src/main/java/author/Author.java
  src/main/java/author/AuthorList.java
  src/main/java/commands/AddAuthorCommand.java
  src/main/java/commands/AddDeadlineCommand.java
  src/main/java/commands/AddMangaCommand.java
  src/main/java/commands/ByeCommand.java
  src/main/java/commands/DeleteAuthorCommand.java
  src/main/java/commands/DeleteDeadlineCommand.java
  src/main/java/commands/DeleteMangaCommand.java
  src/main/java/manga/Manga.java
  src/main/java/manga/MangaList.java
  src/main/java/storage/Storage.java
  src/main/java/tantou/Tantou.java
  src/test/java/author/AuthorListTest.java
  src/test/java/author/AuthorTest.java
  src/test/java/commands/DeleteAuthorCommandTest.java
  src/test/java/commands/DeleteMangaCommandTest.java
  src/test/java/storage/StorageTest.java
  src/test/resources/testCatalog.json
Labels: type.Story, priority.High

#42 Branch refactor catalog
  src/main/java/author/Author.java
  src/main/java/commands/AddAuthorCommand.java
  src/main/java/commands/AddMangaCommand.java
  src/main/java/commands/ByeCommand.java
  src/main/java/commands/Command.java
  src/main/java/commands/GreetCommand.java
  src/main/java/constants/Command.java
  src/main/java/constants/Options.java
  src/main/java/manga/Manga.java
  src/main/java/parser/Parser.java
  src/main/java/tantou/Tantou.java
  src/test/java/commands/AddAuthorCommandTest.java
  src/test/java/commands/AddDeadlineCommandTest.java
  src/test/java/commands/AddMangaCommandTest.java
  src/test/java/commands/DeleteAuthorCommandTest.java
  src/test/java/commands/DeleteDeadlineCommandTest.java
  src/test/java/commands/DeleteMangaCommandTest.java
  src/test/java/parser/ParserTest.java
  text-ui-test/input.txt
Labels: type.Task, priority.High

#48 Update code sections authors for RepoSense
  src/main/java/author/Author.java
  src/main/java/author/AuthorList.java
  src/main/java/commands/ViewAuthorsCommand.java
  src/main/java/commands/ViewMangasCommand.java
  src/main/java/manga/Manga.java
  src/main/java/manga/MangaList.java
  src/main/java/parser/Parser.java
  src/main/java/tantou/Tantou.java
  src/test/java/author/AuthorListTest.java
  src/test/java/author/AuthorTest.java
  src/test/java/manga/MangaListTest.java
  src/test/java/parser/ParserTest.java
Labels: type.Task, priority.Medium

#53 Decouple methods in Storage class
  src/main/java/author/Author.java
  src/main/java/commands/AddMangaCommand.java
  src/main/java/manga/Manga.java
  src/main/java/storage/AuthorDeserializer.java
  src/main/java/storage/ExcludeInSerialization.java
  src/main/java/storage/ExcludeInSerializationAnnotationExclusionStrategy.java
  src/main/java/storage/Storage.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.Medium

#68 Update JavaDoc for Storage constructor
  src/main/java/author/Author.java
  src/main/java/storage/AuthorDeserializer.java
  src/main/java/storage/AuthorListDeserializer.java
  src/main/java/storage/MangaDeserializer.java
  src/main/java/storage/MangaListDeserializer.java
  src/main/java/storage/Storage.java
  src/test/java/storage/AuthorDeserializerTest.java
  src/test/java/storage/AuthorListDeserializerStub.java
  src/test/java/storage/AuthorListDeserializerTest.java
  src/test/java/storage/MangaDeserializerTest.java
  src/test/java/storage/MangaListDeserializerTest.java
  src/test/java/storage/StorageTest.java
Labels: type.Task, priority.High

#71 Create utility class StorageHelper
  src/main/java/commands/AddAuthorCommand.java
  src/main/java/commands/AddMangaCommand.java
  src/main/java/commands/AddSalesCommand.java
  src/main/java/commands/ByeCommand.java
  src/main/java/commands/DeleteAuthorCommand.java
  src/main/java/commands/DeleteMangaCommand.java
  src/main/java/storage/StorageHelper.java
Labels: type.Task, priority.Low

#83 Update view command parser and add JavaDoc
  src/main/java/author/AuthorList.java
  src/main/java/commands/AddAuthorCommand.java
  src/main/java/commands/AddMangaCommand.java
  src/main/java/commands/AddSalesCommand.java
  src/main/java/commands/DeleteAuthorCommand.java
  src/main/java/commands/ViewAuthorsCommand.java
  src/main/java/commands/ViewMangasCommand.java
  src/main/java/constants/Options.java
  src/main/java/constants/PrintFormat.java
  src/main/java/constants/Regex.java
  src/main/java/exceptions/AuthorNameTooLongException.java
  src/main/java/exceptions/InvalidViewCommandException.java
  src/main/java/exceptions/MangaNameTooLongException.java
  src/main/java/manga/MangaList.java
  src/main/java/parser/Parser.java
  src/main/java/ui/PrintColumn.java
  src/main/java/ui/Ui.java
  src/test/java/commands/AddAuthorCommandTest.java
  src/test/java/commands/AddMangaCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#76 Update DeveloperGuide.md with storage and view command implementation
  .gitignore
  build.gradle
  docs/DeveloperGuide.md
  docs/uml/images/Command.png
  docs/uml/puml/.PlantUMLClass.config
  docs/uml/puml/.PlantUMLSequence.config
  docs/uml/puml/AuthorListClass/AuthorListClass.png
  docs/uml/puml/AuthorListClass/AuthorListClass.puml
  docs/uml/puml/Command/Command.png
  docs/uml/puml/Command/Command.puml
  docs/uml/puml/SavingDataSequence/SavingDataSequence.png
  docs/uml/puml/SavingDataSequence/SavingDataSequence.puml
  docs/uml/puml/SavingDataSequence/refGetStorageInstanceSequence.png
  docs/uml/puml/SavingDataSequence/refGetStorageInstanceSequence.puml
  docs/uml/puml/StorageClass/StorageClass.png
  docs/uml/puml/StorageClass/StorageClass.puml
  docs/uml/puml/UiClass/UiClass.png
  docs/uml/puml/UiClass/UiClass.puml
  docs/uml/puml/ViewMangaSequence/ViewMangaSequence.png
  docs/uml/puml/ViewMangaSequence/ViewMangaSequence.puml
  docs/uml/puml/ViewMangaSequence/refGetColumnsToPrintSequence.png
  docs/uml/puml/ViewMangaSequence/refGetColumnsToPrintSequence.puml
  docs/uml/puml/ViewMangaSequence/refPrintRowsSequence.png
  docs/uml/puml/ViewMangaSequence/refPrintRowsSequence.puml
  src/main/java/Main.java
  src/main/java/storage/AuthorListDeserializer.java
  src/main/java/storage/MangaListDeserializer.java
  src/main/java/storage/Storage.java
  src/main/java/storage/StorageHelper.java
  src/main/java/tantou/Tantou.java
  src/main/java/ui/PrintColumn.java
Labels: type.Task, priority.High

#95 Address comments made by TA and peers on branch-address-feedback
  docs/uml/puml/.PlantUMLClass.config
  docs/uml/puml/.PlantUMLSequence.config
  docs/uml/puml/AuthorListClass/AuthorListClass.png
  docs/uml/puml/Command/Command.png
  docs/uml/puml/SavingDataSequence/SavingDataSequence.png
  docs/uml/puml/SavingDataSequence/refGetStorageInstanceSequence.png
  docs/uml/puml/SavingDataSequence/refGetStorageInstanceSequence.puml
  docs/uml/puml/StorageClass/StorageClass.png
  docs/uml/puml/UiClass/UiClass.png
  docs/uml/puml/UiClass/UiClass.puml
  docs/uml/puml/ViewMangaSequence/ViewMangaSequence.png
  docs/uml/puml/ViewMangaSequence/ViewMangaSequence.puml
  docs/uml/puml/ViewMangaSequence/refGetColumnsToPrintSequence.png
  docs/uml/puml/ViewMangaSequence/refGetColumnsToPrintSequence.puml
  docs/uml/puml/ViewMangaSequence/refPrintRowsSequence.png
  docs/uml/puml/ViewMangaSequence/refPrintRowsSequence.puml
Labels: type.Bug, severity.Low
